---
# tasks file for haproxy
- name: Initiating task if ansible_os_family = Debian
  when: ansible_os_family=="Debian"
  include_tasks: Debian.yml
  
- name: Initiating task if ansible_os_family = RedHat
  when: ansible_os_family=="RedHat"
  include_tasks: RedHat.yml
